Config-Format: 1.0
#Do not touch or delete!

Recipes:
  #EXAMPLES:
  Toast:
    Name: "&6Toast"
    #Name of the food (what the item will show up as)
    Recipe-Type: "Furnace"
    #What crafting station is this food made at? Options are Furnace, Smoker, Campfire, Blast Furnace, Shaped, and Shapeless.
    Lore:
    - "&bmmm... toasty"
    #The lore of the item, only one string supported for now
    Recipe:
      Ingredient: "BREAD"
      #The item going into the furnace
      Cook-Time: 100
      #How long, in ticks, the food will take to cook
      Experience: 5
      #Amount of experience rewarded for cooking
      Amount: 1
      #The amount produced by the recipe.
    Base: "BREAD"
    #What the new food will appear as in your hand. The texture can be changed via resource pack.
    Hunger-Fill: 6
    #How much hunger it will fill. 1 = half a hunger bar 20 = full hunger.
    Saturation: 5
    #How much saturation it will restore. same formula as hunger fill, but with decimals.
    Id: 1
    #Tells my plugin what food you're eating!
    #Also allows for Custom Models with a resource pack.
    #This MUST be unique for every different food!

  BaconBurger:
    Name: "&6Bacon Burger"
    Recipe-Type: "Shaped"
    Lore:
    - "&bTasty Burger"
    Recipe:
      TableLine1: " B "
      TableLine2: "KMS"
      TableLine3: " B "
      #The shape of the recipe in the crafting table. Put a letter for an item and a space to leave it blank. MUST HAVE 3 CHARACTERS IN EACH!
      LetterKeys:
        B: "BREAD"
        K: "DRIED_KELP"
        M: "COOKED_BEEF"
        S: "CFD-Bacon"
      Amount: 1
      #What materials the letters in the recipe are representing.
      #Use "CFD-[FoodConfigName]" to use a custom food in the crafting recipe of another custom food
    Base: "COOKED_BEEF"
    Hunger-Fill: 10
    Saturation: 6.5
    Id: 2
#Incompatible with 1.13!

  Chocolatebar:
    Name: "&6Chocolate Bar"
    Recipe-Type: "Shaped"
    Lore:
    - "&bmmmm... chocolatey"
    Recipe:
      TableLine1: "   "
      TableLine2: "CMC"
      TableLine3: "CCC"
      LetterKeys:
        C: "COCOA_BEANS"
        M: "MILK_BUCKET"
      Amount: 1
    Base: "DRIED_KELP"
    Hunger-Fill: 3
    Saturation: 3.2
    Id: 3

  Bakedapple:
    Name: "&6Baked Apple"
    Recipe-Type: "Furnace"
    Lore:
    - "&bAn apple and an open flame makes for a succulent treat"
    Recipe:
      Ingredient: "APPLE"
      Cook-Time: 55
      Experience: 5
      Amount: 1
    Base: "APPLE"
    Hunger-Fill: 5
    Saturation: 4
    Id: 4

  Bacon:
    Name: "&6Bacon"
    Recipe-Type: "None"
    Lore:
    - "&bGreasy..."
    Base: "COOKED_PORKCHOP"
    Hunger-Fill: 5
    Saturation: 5.4
    Id: 5

  Smokedapple:
    Name: "&6Smoked Apple"
    Recipe-Type: "Smoker"
    Lore:
    - "&bReally just a smoker recipe test, otherwise identical to baked apple"
    Recipe:
      Ingredient: "APPLE"
      Cook-Time: 55
      Experience: 5
      Amount: 1
    Base: "APPLE"
    Hunger-Fill: 5
    Saturation: 2.1
    Id: 6

  Woodsmokedapple:
    Name: "&6Wood Smoked Apple"
    Recipe-Type: "Campfire"
    Lore:
    - "&bReally just a campfire recipe test, otherwise identical to baked apple"
    Recipe:

      Ingredient: "APPLE"
      Cook-Time: 55
      Experience: 5
      Amount: 1
    Base: "APPLE"
    Hunger-Fill: 5
    Saturation: 2.2
    Id: 7

  Chickenkebab:
    Name: "&6Chicken Kebab"
    Recipe-Type: "Shapeless"
    Lore:
    - "&bIt tastes like chicken..."
    Recipe:
      Amount: 2
      Ingredients:
        STICK: 2
        COOKED_CHICKEN: 1
    Base: "COOKED_CHICKEN"
    Hunger-Fill: 3
    Saturation: 5.5
    Id: 8

  PoisonedGrass:
    Name: "&2Poisoned Grass"
    Recipe-Type: "None"
    Lore:
    - "&bIt doesn't seem edible..."
    Base: "DRIED_KELP"
    Hunger-Fill: 2
    Saturation: 0.1
    Id: 9
    #Example of potion effects on foods:
    Effects:
      POISON:
      #Open with the potion effect Type (found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html)
        Duration: 60
        #Duration in ticks (20 ticks per second)
        Amplifier: 0
        #Amplifier is the level minus one, so Poison 2 has an amplifier of 1
      CONFUSION:
      #Confusion = nausea
        Duration: 40
        Amplifier: 0

  GoldenChicken:
    Name: "&6Golden Chicken"
    Recipe-Type: "none"
    Lore:
    - "&bIt tastes like metal..."
    #Example of commands on foods:
    #Commands are executed at the console level
    Commands:
      - eco give %player% 10
    Base: "COOKED_CHICKEN"
    Hunger-Fill: 3
    Saturation: 3
    Id: 10

  CoalBlastedApple:
    Name: "&6Coal Blasted Apple"
    Recipe-Type: "Blast Furnace"
    Lore:
      - "&bReally just a blast furnace recipe test, otherwise identical to baked apple"
    Recipe:
      Ingredient: "APPLE"
      Cook-Time: 55
      Experience: 5
      Amount: 1
    Base: "APPLE"
    Hunger-Fill: 5
    Saturation: 2.2
    Id: 11